apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - files/gen-istio.yaml

patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: istiod
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/args/-1
        value: "--tlsCertFile=/etc/cert-manager/tls/tls.crt"